### ISSUE TITLE
Unique validation

### ISSUE THREAD

**Issue by d13r** [JeffreyWay/Laravel-Model-Validation#2]
The [`unique` validation](http://four.laravel.com/docs/validation#rule-unique) accepts the ID of the current row to ignore. Since the rules are set statically, is there any way to provide this?

**Comment by JonoB** [comment]
This is how I do it:

``` php
public static $rules = array(
    'name' => 'required|unique:widgets,name,:id',
);

public function validate()
{
    // if the key's value is greater than 0, then its an existing model
    // so we will replace the placeholder (:id) with the id value
    // otherwise we will just replace it with an empty string
    $replace = ($this->getKey() > 0) ? $this->getKey() : '';
    foreach (static::$rules as $key => $rule)
    {
        static::$rules[$key] = str_replace(':id', $replace, $rule);
    }

    $validator = $this->validator->make($this->attributes, static::$rules, static::$messages);

    if ($validator->passes()) return true;

    $this->setErrors($validator->messages());

    return false;
}
```

**Comment by andrewdelprete** [comment]
JonoB I know this is 8 months old but is this still how you're solving this issue? what do I do with the $messages variable in your example?

**Comment by andrewdelprete** [comment]
I figured it out. Thanks

**Comment by elathon** [comment]
The above threw an error "Access to undeclared static property: User::$messages"

I added this to the User model:

`protected static $messages = [];`

Which seems to have fixed it. Not sure if this is the right way to go about it.
