### ISSUE TITLE
Update composer.json to work with Laravel 4.1

### ISSUE THREAD

**Issue by austinheap** [JeffreyWay/Laravel-Model-Validation#9]
Cannot upgrade projects using this to Laravel 4.1 because the composer.json is "4.0.x". Other packages have been changing theirs simple to "4.x".

**Comment by yaapis** [comment]
The same issue. Update composer to L 4.1 please.

**Comment by johndwells** [comment]
Just ran into this as well.

**Comment by Burnett01** [comment]
Yes please fix it

**Comment by sercanvirlan** [comment]
Jeffrey give some time to this issue please :)

**Comment by sahanh** [comment]
for the time being you guys can reference a custom vcs in composer.json https://gist.github.com/sahanh/8862355

```
"repositories": [
    {
        "type" : "vcs",
        "url"  : "git@github.com:sahanh/Laravel-Model-Validation.git"
     }
],
```

**Comment by RSully** [comment]
Same issue here

**Comment by JeffreyWay** [comment]
ok -done.
